name: radioshow_avatar
description: "Avator animator"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.17.0
  cupertino_icons: ^1.0.2
  window_manager: ^0.3.9
  mic_stream: ^0.7.1+2
  audio_monitor:
    path: packages/audio_monitor

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
